### ISSUE TITLE
When i try to download reels with it.. it says "Not supported" (Log Details inside)

### ISSUE THREAD

**Issue by NomanBaigA** [KishanViramgama/InstagramDownloader#8]
2022-07-18 15:25:55.015 13190-13190/com.app.instancedownload W/System.err: org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
2022-07-18 15:25:55.015 13190-13190/com.app.instancedownload W/System.err:     at org.json.JSON.typeMismatch(JSON.java:112)
2022-07-18 15:25:55.015 13190-13190/com.app.instancedownload W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:169)
2022-07-18 15:25:55.015 13190-13190/com.app.instancedownload W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:182)
2022-07-18 15:25:55.015 13190-13190/com.app.instancedownload W/System.err:     at com.app.instancedownload.util.FindData$1.onSuccess(FindData.java:49)
2022-07-18 15:25:55.016 13190-13190/com.app.instancedownload W/System.err:     at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:354)
2022-07-18 15:25:55.016 13190-13190/com.app.instancedownload W/System.err:     at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:513)
2022-07-18 15:25:55.016 13190-13190/com.app.instancedownload W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2022-07-18 15:25:55.016 13190-13190/com.app.instancedownload W/System.err:     at android.os.Looper.loop(Looper.java:223)
2022-07-18 15:25:55.016 13190-13190/com.app.instancedownload W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
2022-07-18 15:25:55.016 13190-13190/com.app.instancedownload W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-07-18 15:25:55.016 13190-13190/com.app.instancedownload W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2022-07-18 15:25:55.017 13190-13190/com.app.instancedownload W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by KishanViramgama** [comment]
@NomanBaigA This repository only working on public post download load. If not supported any link then I will showing the message.

**Comment by NomanBaigA** [comment]
> @NomanBaigA This repository only working on public post download load. If not supported any link then I will showing the message.

Yes, I tried with public posts(reels). reels which are available on search

**Comment by KishanViramgama** [comment]
Ok I will check as soon as possible

**Comment by nikhilgodhani08** [comment]
> 2022-07-18 15:25:55.015 13190-13190/com.app.instancedownload W/System.err: org.json.JSONException: Value (JSONObject.java:169) 2022-07-18 15:25:55.015 13190-13190/com.app.instancedownload W/System.err: at org.json.JSONObject.(JSONObject.java:182) 2022-07-18 15:25:55.015 13190-13190/com.app.instancedownload W/System.err: at com.app.instancedownload.util.FindData$1.onSuccess(FindData.java:49) 2022-07-18 15:25:55.016 13190-13190/com.app.instancedownload W/System.err: at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:354) 2022-07-18 15:25:55.016 13190-13190/com.app.instancedownload W/System.err: at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:513) 2022-07-18 15:25:55.016 13190-13190/com.app.instancedownload W/System.err: at android.os.Handler.dispatchMessage(Handler.java:106) 2022-07-18 15:25:55.016 13190-13190/com.app.instancedownload W/System.err: at android.os.Looper.loop(Looper.java:223) 2022-07-18 15:25:55.016 13190-13190/com.app.instancedownload W/System.err: at android.app.ActivityThread.main(ActivityThread.java:7656) 2022-07-18 15:25:55.016 13190-13190/com.app.instancedownload W/System.err: at java.lang.reflect.Method.invoke(Native Method) 2022-07-18 15:25:55.016 13190-13190/com.app.instancedownload W/System.err: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 2022-07-18 15:25:55.017 13190-13190/com.app.instancedownload W/System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

muje bhi same error aa rahi he you find any solution ?

**Comment by KishanViramgama** [comment]
@NomanBaigA and @nikhil888-teach 

- Please check out new version
- Right now only public post download supported
